services:

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - dados:/var/lib/mysql
    networks:
      - petsplace
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: alphonsus
      MYSQL_DATABASE: petsplacedata
      MYSQL_USER: petsplace
      MYSQL_PASSWORD: animalfelix

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - petsplace

  servidor:
    image: node/back:1.0.0
    container_name: servidor
    networks:
      - petsplace
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile

networks:
  petsplace:
    name: petsplace
    driver: bridge

volumes:
  dados:
    name: dados

